import type { Metadata } from "next";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RecipeLayout({}: // children,
Readonly<{
  children?: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <div className="w-full flex gap-2">
        <div className="flex-1">Left</div>
        <div className="flex-1">Right</div>
      </div>
    </div>
  );
}
